"""empty message

Revision ID: 2679e1f18e66
Revises: 10ad0b8c1b7e
Create Date: 2022-08-12 23:27:50.807798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2679e1f18e66'
down_revision = '10ad0b8c1b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
