"""empty message

Revision ID: 903cc678826b
Revises: 531bbb61c35e
Create Date: 2022-08-12 22:33:43.872019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903cc678826b'
down_revision = '531bbb61c35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
