"""empty message

Revision ID: d7597f08697a
Revises: 739f9787569d
Create Date: 2022-08-13 01:36:35.571897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7597f08697a'
down_revision = '739f9787569d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
